package connectors

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"
	"time"
)

func TestImportGitHub_BasicCommits(t *testing.T) {
	repo := setupGitRepo(t, "test@example.com", "Tester", []commitSpec{
		{msg: "Add initial feature", date: "2023-11-14T15:00:00+00:00"},
		{msg: "Fix a bug in the feature", date: "2023-11-14T16:00:00+00:00"},
	})

	result, err := ImportGitHub(GitHubImportOptions{Repos: []string{repo}})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(result) != 2 {
		t.Fatalf("expected 2 commits, got %d", len(result))
	}
	if result[0].Text != "Add initial feature" {
		t.Errorf("expected 'Add initial feature', got %q", result[0].Text)
	}
	if result[0].Metadata["repo"] != filepath.Base(repo) {
		t.Errorf("expected repo name %q, got %v", filepath.Base(repo), result[0].Metadata["repo"])
	}
}

func TestImportGitHub_EmailFilter(t *testing.T) {
	repo := t.TempDir()
	initGitRepo(t, repo)

	// commit from two different authors
	gitCommit(t, repo, "me@example.com", "Me", "My commit", "2023-11-14T15:00:00+00:00")
	gitCommit(t, repo, "other@example.com", "Other", "Other commit", "2023-11-14T16:00:00+00:00")

	result, err := ImportGitHub(GitHubImportOptions{
		Repos: []string{repo},
		Email: "me@example.com",
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(result) != 1 {
		t.Fatalf("expected 1 commit, got %d", len(result))
	}
	if result[0].Text != "My commit" {
		t.Errorf("expected 'My commit', got %q", result[0].Text)
	}
}

func TestImportGitHub_AutoGeneratedFiltering(t *testing.T) {
	tests := []struct {
		subject  string
		filtered bool
	}{
		{"Merge pull request #42 from someone/branch", true},
		{"Merge branch 'main' into feature", true},
		{"Revert \"Some change\"", true},
		{"Auto-merge something", true},
		{"Initial commit", true},
		{"Co-Authored-By: someone", true},
		{"Bump lodash from 4.17.20 to 4.17.21", true},
		{"chore(deps): update dependency", true},
		{"fix: resolve login issue", false},
		{"Add new endpoint for users", false},
	}

	for _, tc := range tests {
		got := isAutoGenerated(tc.subject)
		if got != tc.filtered {
			t.Errorf("isAutoGenerated(%q) = %v, want %v", tc.subject, got, tc.filtered)
		}
	}
}

func TestImportGitHub_SinceFilter(t *testing.T) {
	repo := setupGitRepo(t, "test@example.com", "Tester", []commitSpec{
		{msg: "Old commit", date: "2020-01-01T00:00:00+00:00"},
		{msg: "New commit", date: "2023-11-14T15:00:00+00:00"},
	})

	since := time.Date(2023, 1, 1, 0, 0, 0, 0, time.UTC)
	result, err := ImportGitHub(GitHubImportOptions{
		Repos: []string{repo},
		Since: &since,
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(result) != 1 {
		t.Fatalf("expected 1 commit, got %d", len(result))
	}
	if result[0].Text != "New commit" {
		t.Errorf("expected 'New commit', got %q", result[0].Text)
	}
}

func TestImportGitHub_CommitWithBody(t *testing.T) {
	repo := t.TempDir()
	initGitRepo(t, repo)

	// commit with subject and body
	gitCommitWithBody(t, repo, "test@example.com", "Tester",
		"Add feature X\n\nThis adds feature X with support\nfor multiple lines.",
		"2023-11-14T15:00:00+00:00")

	result, err := ImportGitHub(GitHubImportOptions{Repos: []string{repo}})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(result) != 1 {
		t.Fatalf("expected 1 commit, got %d", len(result))
	}
	if !contains(result[0].Text, "Add feature X") {
		t.Errorf("expected subject in text, got %q", result[0].Text)
	}
	if !contains(result[0].Text, "This adds feature X") {
		t.Errorf("expected body in text, got %q", result[0].Text)
	}
}

func TestImportGitHub_SkipsBadRepo(t *testing.T) {
	// nonexistent repo should be skipped (printed to stderr), not cause error
	result, err := ImportGitHub(GitHubImportOptions{
		Repos: []string{"/nonexistent/repo"},
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(result) != 0 {
		t.Fatalf("expected 0 messages from bad repo, got %d", len(result))
	}
}

func TestImportGitHub_MultipleRepos(t *testing.T) {
	repo1 := setupGitRepo(t, "test@example.com", "Tester", []commitSpec{
		{msg: "Commit in repo1", date: "2023-11-14T15:00:00+00:00"},
	})
	repo2 := setupGitRepo(t, "test@example.com", "Tester", []commitSpec{
		{msg: "Commit in repo2", date: "2023-11-14T16:00:00+00:00"},
	})

	result, err := ImportGitHub(GitHubImportOptions{Repos: []string{repo1, repo2}})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(result) != 2 {
		t.Fatalf("expected 2 commits, got %d", len(result))
	}
}

func TestImportGitHub_NoMerges(t *testing.T) {
	// The git log uses --no-merges, but we also test the isAutoGenerated filter
	// for merge-like subjects. We just verify the auto-generated filter catches them.
	if !isAutoGenerated("Merge pull request #1 from user/branch") {
		t.Error("expected merge PR to be auto-generated")
	}
	if !isAutoGenerated("Merge branch 'main'") {
		t.Error("expected merge branch to be auto-generated")
	}
}

// --- helpers ---

type commitSpec struct {
	msg  string
	date string
}

func setupGitRepo(t *testing.T, email, name string, commits []commitSpec) string {
	t.Helper()
	dir := t.TempDir()
	initGitRepo(t, dir)
	for _, c := range commits {
		gitCommit(t, dir, email, name, c.msg, c.date)
	}
	return dir
}

func initGitRepo(t *testing.T, dir string) {
	t.Helper()
	runGit(t, dir, "init")
	runGit(t, dir, "config", "user.email", "init@example.com")
	runGit(t, dir, "config", "user.name", "Init")
}

func gitCommit(t *testing.T, dir, email, name, msg, date string) {
	t.Helper()
	// create a unique file to have something to commit
	f, err := os.CreateTemp(dir, "file-*.txt")
	if err != nil {
		t.Fatalf("create temp file: %v", err)
	}
	f.WriteString(msg)
	f.Close()

	runGit(t, dir, "add", filepath.Base(f.Name()))

	cmd := exec.Command("git", "-C", dir, "commit", "-m", msg)
	cmd.Env = append(os.Environ(),
		"GIT_AUTHOR_EMAIL="+email,
		"GIT_AUTHOR_NAME="+name,
		"GIT_COMMITTER_EMAIL="+email,
		"GIT_COMMITTER_NAME="+name,
		"GIT_AUTHOR_DATE="+date,
		"GIT_COMMITTER_DATE="+date,
	)
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git commit failed: %v\n%s", err, out)
	}
}

func gitCommitWithBody(t *testing.T, dir, email, name, fullMsg, date string) {
	t.Helper()
	f, err := os.CreateTemp(dir, "file-*.txt")
	if err != nil {
		t.Fatalf("create temp file: %v", err)
	}
	f.WriteString(fullMsg)
	f.Close()

	runGit(t, dir, "add", filepath.Base(f.Name()))

	cmd := exec.Command("git", "-C", dir, "commit", "-m", fullMsg)
	cmd.Env = append(os.Environ(),
		"GIT_AUTHOR_EMAIL="+email,
		"GIT_AUTHOR_NAME="+name,
		"GIT_COMMITTER_EMAIL="+email,
		"GIT_COMMITTER_NAME="+name,
		"GIT_AUTHOR_DATE="+date,
		"GIT_COMMITTER_DATE="+date,
	)
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git commit failed: %v\n%s", err, out)
	}
}

func runGit(t *testing.T, dir string, args ...string) {
	t.Helper()
	fullArgs := append([]string{"-C", dir}, args...)
	cmd := exec.Command("git", fullArgs...)
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git %v failed: %v\n%s", args, err, out)
	}
}
