package connectors

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/jschell12/replicateme/pkg/corpus"
)

// GitHubImportOptions controls GitHub/git-log import.
type GitHubImportOptions struct {
	Repos []string // paths to local git repos
	Email string   // git author email to filter
	Since *time.Time
}

// ImportGitHub reads commit messages from local git repositories.
func ImportGitHub(opts GitHubImportOptions) ([]corpus.RawMessage, error) {
	var messages []corpus.RawMessage

	for _, repo := range opts.Repos {
		commits, err := getCommits(repo, opts.Email, opts.Since)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Skipping %s: %v\n", repo, err)
			continue
		}
		messages = append(messages, commits...)
	}

	sort.Slice(messages, func(i, j int) bool {
		return messages[i].Timestamp.Before(messages[j].Timestamp)
	})
	return messages, nil
}

func getCommits(repoPath, email string, since *time.Time) ([]corpus.RawMessage, error) {
	// format: \x1f<hash>\x1f<timestamp>\x1f<subject>\x1f<body>\x1e
	const sep = "\x1f"
	const end = "\x1e"

	args := []string{"-C", repoPath, "log"}

	if email != "" {
		args = append(args, fmt.Sprintf("--author=%s", email))
	}
	if since != nil {
		args = append(args, fmt.Sprintf("--since=%s", since.Format(time.RFC3339)))
	}

	args = append(args, fmt.Sprintf("--format=%s%%H%s%%aI%s%%s%s%%b%s", sep, sep, sep, sep, end))
	args = append(args, "--no-merges")

	cmd := exec.Command("git", args...)
	cmd.Env = append(os.Environ(), "GIT_TERMINAL_PROMPT=0")
	output, err := cmd.Output()
	if err != nil {
		return nil, err
	}

	var messages []corpus.RawMessage
	entries := strings.Split(string(output), end)

	for _, entry := range entries {
		entry = strings.TrimSpace(entry)
		if entry == "" {
			continue
		}
		parts := strings.Split(entry, sep)
		// filter empty strings from split
		var filtered []string
		for _, p := range parts {
			if p != "" {
				filtered = append(filtered, p)
			}
		}
		if len(filtered) < 3 {
			continue
		}

		hash := filtered[0]
		dateStr := filtered[1]
		subject := filtered[2]
		var bodyParts []string
		if len(filtered) > 3 {
			bodyParts = filtered[3:]
		}

		body := strings.TrimSpace(strings.Join(bodyParts, "\n"))
		fullMessage := subject
		if body != "" {
			fullMessage = subject + "\n\n" + body
		}

		if isAutoGenerated(subject) {
			continue
		}

		ts, err := time.Parse(time.RFC3339, dateStr)
		if err != nil {
			continue
		}

		repoName := filepath.Base(repoPath)

		messages = append(messages, corpus.RawMessage{
			ID:         fmt.Sprintf("github-%s", hash[:8]),
			Text:       fullMessage,
			Platform:   corpus.GitHub,
			Timestamp:  ts.UTC(),
			IsFromUser: true,
			Metadata: map[string]any{
				"type": "commit",
				"repo": repoName,
				"hash": hash[:8],
			},
		})
	}

	return messages, nil
}

var autoGeneratedPatterns = []*regexp.Regexp{
	regexp.MustCompile(`(?i)^Merge (pull request|branch)`),
	regexp.MustCompile(`(?i)^Revert "`),
	regexp.MustCompile(`(?i)^Auto-merge`),
	regexp.MustCompile(`(?i)^Initial commit$`),
	regexp.MustCompile(`(?i)^Co-Authored-By:`),
	regexp.MustCompile(`(?i)^Bump \w+ from`),
	regexp.MustCompile(`(?i)^chore\(deps\)`),
}

func isAutoGenerated(subject string) bool {
	for _, p := range autoGeneratedPatterns {
		if p.MatchString(subject) {
			return true
		}
	}
	return false
}
