import { execSync } from "child_process";
import type { RawMessage } from "../corpus/types.js";

// GitHub connector reads from local git repos.
// Pulls commit messages, PR descriptions, and issue comments
// from git log. No API key needed.

export interface GitHubImportOptions {
  repos: string[]; // paths to local git repos
  email?: string; // git author email to filter
  since?: Date;
}

export function importGitHub(opts: GitHubImportOptions): RawMessage[] {
  const messages: RawMessage[] = [];

  for (const repo of opts.repos) {
    try {
      const commits = getCommits(repo, opts.email, opts.since);
      messages.push(...commits);
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      console.warn(`Skipping ${repo}: ${msg}`);
    }
  }

  messages.sort((a, b) => a.timestamp.getTime() - b.timestamp.getTime());
  return messages;
}

function getCommits(
  repoPath: string,
  email?: string,
  since?: Date
): RawMessage[] {
  const args = ["git", "-C", repoPath, "log"];

  if (email) {
    args.push(`--author=${email}`);
  }

  if (since) {
    args.push(`--since=${since.toISOString()}`);
  }

  // format: hash<SEP>timestamp<SEP>subject<SEP>body
  const SEP = "\x1f"; // ASCII unit separator - won't appear in commit messages
  const END = "\x1e"; // ASCII record separator
  args.push(`--format=${SEP}%H${SEP}%aI${SEP}%s${SEP}%b${END}`);
  args.push("--no-merges");

  let output: string;
  try {
    output = execSync(args.join(" "), {
      encoding: "utf-8",
      maxBuffer: 50 * 1024 * 1024,
    });
  } catch {
    return [];
  }

  const messages: RawMessage[] = [];
  const entries = output.split(END).filter((s) => s.trim());

  for (const entry of entries) {
    const parts = entry.split(SEP).filter((s) => s.length > 0);
    if (parts.length < 3) continue;

    const [hash, dateStr, subject, ...bodyParts] = parts;
    if (!hash || !dateStr || !subject) continue;

    const body = bodyParts.join("\n").trim();
    const fullMessage = body ? `${subject}\n\n${body}` : subject;

    // skip auto-generated commit messages
    if (isAutoGenerated(subject)) continue;

    const timestamp = new Date(dateStr);

    messages.push({
      id: `github-${hash.substring(0, 8)}`,
      text: fullMessage,
      platform: "github",
      timestamp,
      isFromUser: true,
      metadata: {
        type: "commit",
        repo: repoPath.split("/").pop(),
        hash: hash.substring(0, 8),
      },
    });
  }

  return messages;
}

function isAutoGenerated(subject: string): boolean {
  const patterns = [
    /^Merge (pull request|branch)/i,
    /^Revert "/i,
    /^Auto-merge/i,
    /^Initial commit$/i,
    /^Co-Authored-By:/i,
    /^Bump \w+ from/i,
    /^chore\(deps\)/i,
  ];
  return patterns.some((p) => p.test(subject));
}
