package portable

import (
	"fmt"
	"os"
	"strings"

	"github.com/jschell12/replicateme/pkg/corpus"
	"github.com/jschell12/replicateme/pkg/style"
)

// ExportRule generates a markdown rule file from the local corpus.
// This file works as:
//   - Claude Code rule (~/.claude/rules/ or .claude/rules/)
//   - Cursor rule (.cursor/rules/)
//   - ChatGPT custom instructions (paste the content)
//   - replicateme --persona flag
//
// No raw messages are included. Only statistical patterns and
// writing guidelines derived from the corpus.
func ExportRule(personaPath string) (string, error) {
	combined, err := corpus.GetProfile("combined")
	if err != nil || combined == nil {
		return "", fmt.Errorf("no profile found. Run `replicateme ingest` first")
	}

	var b strings.Builder

	b.WriteString("# My writing style\n\n")
	b.WriteString("When writing as me, match these patterns. This file was generated by replicateme from my actual messages.\n\n")

	// include persona spec if provided
	if personaPath != "" {
		data, err := os.ReadFile(personaPath)
		if err == nil && len(data) > 0 {
			b.WriteString(string(data))
			b.WriteString("\n\n")
		}
	}

	b.WriteString("## Writing patterns\n\n")
	b.WriteString(style.StyleProfileToPrompt(combined.Profile))
	b.WriteString("\n\n")

	// per-platform breakdown if multiple sources
	allProfiles, _ := corpus.GetAllProfiles()
	var platforms []corpus.PlatformProfile
	for _, p := range allProfiles {
		if p.Platform != "combined" {
			platforms = append(platforms, p)
		}
	}

	if len(platforms) > 1 {
		b.WriteString("## Platform differences\n\n")
		b.WriteString("I write differently depending on context:\n\n")
		for _, p := range platforms {
			fmt.Fprintf(&b, "**%s** (%d messages): avg %d chars, ",
				p.Platform, p.MessageCount, p.Profile.AverageLength)
			fmt.Fprintf(&b, "capitalizes %.0f%%, periods %.0f%%, fragments %.0f%%\n\n",
				p.Profile.CapitalizesFirstWord*100,
				p.Profile.UsesPeriods*100,
				p.Profile.SentenceFragmentRatio*100)
		}
	}

	b.WriteString("## How to apply\n\n")
	b.WriteString("- Match my typical message length for the platform\n")
	b.WriteString("- Casual contexts (texts, Slack, Discord): use more of my shortcuts and quirks\n")
	b.WriteString("- Formal contexts (email, docs, PRs): keep my voice but use cleaner grammar\n")
	b.WriteString("- If I rarely use periods, don't add periods\n")
	b.WriteString("- If I rarely capitalize, don't capitalize\n")
	b.WriteString("- Use my common phrases naturally\n")

	return b.String(), nil
}

// ExportRuleToFile writes the rule to a markdown file.
func ExportRuleToFile(path string, personaPath string) error {
	rule, err := ExportRule(personaPath)
	if err != nil {
		return err
	}
	return os.WriteFile(path, []byte(rule), 0644)
}

// EnrichRule reads an existing rule file and appends local corpus
// data to it. Use this on a work machine after ingesting work-specific
// messages (e.g. Slack) to add those patterns to the rule without
// losing the personal data that was already in it.
func EnrichRule(rulePath string) (string, error) {
	existing, err := os.ReadFile(rulePath)
	if err != nil {
		return "", fmt.Errorf("reading rule file: %w", err)
	}

	// check if there's local corpus data to add
	stats, err := corpus.GetCorpusStats()
	if err != nil || stats.TotalMessages == 0 {
		return string(existing), nil // nothing to add
	}

	allProfiles, _ := corpus.GetAllProfiles()
	if len(allProfiles) == 0 {
		return string(existing), nil
	}

	var b strings.Builder
	b.WriteString(string(existing))

	// add a separator and the local data
	b.WriteString("\n\n---\n\n")
	b.WriteString("## Additional patterns (added by replicateme on this machine)\n\n")

	for _, p := range allProfiles {
		if p.Platform == "combined" {
			continue
		}
		fmt.Fprintf(&b, "### %s (%d messages)\n\n", p.Platform, p.MessageCount)
		b.WriteString(style.StyleProfileToPrompt(p.Profile))
		b.WriteString("\n\n")
	}

	return b.String(), nil
}

// EnrichRuleFile reads, enriches, and writes back the rule file.
func EnrichRuleFile(path string) error {
	enriched, err := EnrichRule(path)
	if err != nil {
		return err
	}
	return os.WriteFile(path, []byte(enriched), 0644)
}
