// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function Generate(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Generate'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAllProfiles() {
  return window['go']['main']['App']['GetAllProfiles']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCorpusStats() {
  return window['go']['main']['App']['GetCorpusStats']();
}

export function GetModels(arg1, arg2) {
  return window['go']['main']['App']['GetModels'](arg1, arg2);
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GetSources() {
  return window['go']['main']['App']['GetSources']();
}

export function IngestSource(arg1, arg2, arg3) {
  return window['go']['main']['App']['IngestSource'](arg1, arg2, arg3);
}

export function IsRAGAvailable() {
  return window['go']['main']['App']['IsRAGAvailable']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
