// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {corpus} from '../models';
import {config} from '../models';
import {main} from '../models';

export function CopyToClipboard(arg1:string):Promise<void>;

export function Generate(arg1:string,arg2:string,arg3:number,arg4:string,arg5:number):Promise<Array<string>>;

export function GetAllProfiles():Promise<Array<corpus.PlatformProfile>>;

export function GetConfig():Promise<config.Config>;

export function GetCorpusStats():Promise<corpus.CorpusStats>;

export function GetModels(arg1:string,arg2:string):Promise<Array<string>>;

export function GetProfile(arg1:string):Promise<corpus.ProfileResult>;

export function GetSources():Promise<Array<main.SourceInfo>>;

export function IngestSource(arg1:string,arg2:string,arg3:Record<string, string>):Promise<main.IngestResult>;

export function IsRAGAvailable():Promise<boolean>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SelectFile():Promise<string>;
